### PR TITLE
[Lesson 7] Change OMDB API to Netflix Roulette API

### PR DESCRIPTION
**Pull request by VasilyShelkov**
I decided to use this [Netflix API](http://netflixroulette.net/api/) instead of the Studio Ghibli one. Only reason is because the Studio Ghibli API didn't have any kind of images or posters and I felt that visual aspect will keep users a bit more engaged. Unfortunately the Netflix one is the only one that I found which has images and does not require any kind of API Key

Hopefully this is still suitable, I also mentioned that readers welcome to use any other API from the github public APIs repo which is linked.

If it's not, please point me to a more suitable API and I'll be happy to adjust

### CODE REVIEW

**Comment by VasilyShelkov** [comment]
OOOHHHH actually realised that I haven't changed the image URLS, where's easiest to host for the images ? Currently it's being hosted in https://cloud.githubusercontent.com/assets/50838/25059880/ecaf70d2-21ac-11e7-8c3e-a7a697628643.png ... I'm not familiar with this resource

**Comment by arunoda** [comment]
Thanks.
We've another PR here.
I like that too: https://github.com/arunoda/learnnextjs-content/pull/21

**Comment by VasilyShelkov** [comment]
Ah damn, should I just close this then ? Didn't see that one, my bad 😞 I don't mind which is used

**Comment by VasilyShelkov** [comment]
Well I've added the replacement images, check they're ok if you're going to merge this PR, otherwise won't be offended if you close this for the other PR. I did open this after the other not checking the PRs first :S

**Comment by arunoda** [comment]
Thanks a lot @VasilyShelkov.
I'm gonna try these updated lessons and I'll pick a one.

**Comment by arunoda** [comment]
Hey, thanks again. I've took the other PR and deployed: https://learnnextjs.com/basics/fetching-data-for-pages

**Pull request closed without merging**
